name: Java compiler
on:
   workflow_dispatch:
    inputs:
      parameter_name:
        description: 'Release version'
        required: false
        default: '2.1'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17

      - name: Run Allure Report
        run: mvn clean test allure:report
        
 
      - name: Load test report history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
           ref: gh-pages
           path: gh-pages
    
    

      - name: Allure Report action
        uses: simple-elf/allure-report-action@master
        #uses: ./allure-report-action
        if: always()
        #id: allure-report
        with:
          allure_results: build/allure-results
          allure_history: allure-history/allure-history
          keep_reports: 3

 


      - name: Deploy report to GitHub Pages 🚀
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         publish_branch: gh-pages
         publish_dir: allure-history


