name: Java Maven Allure Report

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Build with Maven
      run: |
        mvn clean install

    

    # - name: Install dependencies and run tests
    #   run: |
    #     npm install
    #     npm test

    - name: Run Allure Report
      run: |
        mvn test allure:report

    - name: Generate Allure report
      run: |
        allure generate -c -o allure-results

    - name: Publish Allure report
      uses: allure-framework/allure-github-action@v2
      with:
        allure-result-path: allure-results


