name: Java Maven Allure Report

on:
  workflow_dispatch:
    inputs:
      parameter_name:
        description: 'Description of the parameter'
        required: false
        default: 'default_value'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven

    - name: Build with Maven
      run: mvn -B clean test

    - name: Generate Allure Report
      run: mvn allure:report

    - name: Store Allure Results
      uses: actions/upload-artifact@v2
      with:
        name: allure-results
        path: target/allure-results

  allure:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download Allure Results
      uses: actions/download-artifact@v2
      with:
        name: allure-results

    - name: Set up Allure
      uses: actions/setup-allure@v2
      with:
        version: '2.16.0' # Use the latest version available

    - name: Serve Allure Report
      run: allure serve target/allure-results

    - name: Save Allure History
      run: mv target/allure-results/history allure-history

    - name: Deploy report to Github Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: allure-history
