name: Java Maven Allure Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Build with Maven
      run: mvn clean install

  allure-report:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download Allure Report
      uses: actions/download-artifact@v2
      with:
        name: allure-report
        path: target/allure-results

    - name: Set up Allure
      uses: actions/setup-allure@v2
      with:
        version: '2.14.0' # Use the latest version available

    - name: Serve Allure Report
      run: allure serve target/allure-results

  deploy:
    runs-on: ubuntu-latest
    needs: allure-report

    steps:
    - name: Deploy to production
      # Add your deployment steps here
      run: echo "Deploying the code to production"

