name: Java Maven Allure Report

on:
   workflow_dispatch:
    inputs:
      parameter_name:
        description: 'Release version'
        required: false
        default: '2.1'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        
      
    - name: Build with Maven and Execute the Tests
      run: mvn -B clean compile test

    - name: Run Allure Report
      run: mvn clean test allure:report

    - name: Get Allure history
      uses: actions/checkout@v4
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages
        
    - uses: actions/upload-artifact@master
      with:
        name: allure-results
        path: allure-results
        retention-days: 20
        

    # - name: Test marketplace action
    #   uses: simple-elf/allure-report-action@master
    #   if: always()
    #   id: allure-report
    #   with:
    #     allure_results: allure-results
    #     gh_pages: gh-pages
    #     allure_report: allure-report
    #     allure_history: allure-history
    #     keep_reports: 20
        
    - name: Build test report
      uses: simple-elf/allure-report-action@v1.7
      if: always()
      with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: build/allure-results



    - name: Deploy report to GitHub Pages 🚀
      uses: peaceiris/actions-gh-pages@v3
      if: always()
      with:
      # enable_jekyll: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: allure-history

   
